[build]
  command = "npm run build -- --configuration production"
  publish = "dist/PROJECT_NAME"      # ersetze PROJECT_NAME durch deinen Build-Ordner


[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

