@'
[build]
  command = "npm run netlify:build"
  publish = "dist/it-services"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
'@ | Set-Content -Path .\netlify.toml

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    canonicalUrl = "https://www.sakaits.com"
